version: 2
updates:
  - package-ecosystem: "docker-compose"
    directories:
      - "/pihole"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directories:
    schedule:
      interval: "daily"
